-- DabbaMap — 144 claimable stub listings with pre-computed coordinates
-- Paste this entire block into the Supabase SQL editor and click Run.
-- stub=true  →  "Claim this listing" button is visible on each card.
-- is_claimed=false  →  listing is open for anyone to claim.
-- lat/lng are baked in — no geocoding needed. Positions are within ~3 km of each area centre.

INSERT INTO public.listings (name, area, type, cuisines, meals, trial, description, stub, is_claimed, lat, lng)
VALUES
('Vrindawan Tiffin Service',         'Vikhroli East, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1085, 72.9311),
('Sindhfully Yours',                  'Borivali West, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2351, 72.8561),
('Sindhfully Yours',                  'Andheri East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1199, 72.8699),
('Tiffin Daksha',                     'Malad West, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1864, 72.8393),
('Tiffin Daksha',                     'Goregaon West, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1586, 72.8465),
('Ajicha Dabba',                      'Kandivali West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2021, 72.8344),
('Ajicha Dabba',                      'Andheri West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1367, 72.8313),
('Spicey Dicey',                      'Santacruz West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0815, 72.8487),
('Spicey Dicey',                      'Juhu, Mumbai',                       'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1073, 72.8261),
('Calorie Care',                      'Lower Parel, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9985, 72.8316),
('Sanju Sarma Tiffin Services',       'Goregaon East, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1636, 72.8678),
('Sanju Sarma Tiffin Services',       'Malad East, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1875, 72.8575),
('Annu''s Kitchen',                   'Churchgate, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9356, 72.8271),
('Annu''s Kitchen',                   'Bandra West, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0602, 72.8365),
('Twisted Tiffin',                    'Prabhadevi, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0163, 72.8256),
('Dadis Theple',                      'Malad West, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1894, 72.8363),
('Dadis Theple',                      'Kandivali East, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2066, 72.8539),
('Agrawal''s Food Services',          'Andheri East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1239, 72.8729),
('Agrawal''s Food Services',          'Kurla West, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0720, 72.8808),
('Fudpro',                            'Mulund West, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1706, 72.9580),
('Fudpro',                            'Bhandup West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1435, 72.9394),
('Kaka Kaki',                         'Worli, Mumbai',                      'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0075, 72.8176),
('Greencrunch',                       'Thane West',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1946, 72.9632),
('Greencrunch',                       'Mulund East, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1767, 72.9689),
('Greencrunch',                       'Kalwa, Thane',                       'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1793, 73.0100),
('Greencrunch',                       'Bhandup East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1449, 72.9481),
('Ritus Home Kitchen',                'Powai, Mumbai',                      'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1197, 72.9060),
('Ritus Home Kitchen',                'Chandivali, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1085, 72.9149),
('Ritus Home Kitchen',                'Andheri East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1169, 72.8749),
('Delicious Point',                   'Borivali East, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2295, 72.8698),
('Delicious Point',                   'Kandivali West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2061, 72.8374),
('Delicious Point',                   'Dahisar West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2518, 72.8408),
('Sanjana''s Food Studio',            'Andheri West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1407, 72.8343),
('Sanjana''s Food Studio',            'Borivali West, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2381, 72.8531),
('Ghar Ka',                           'Vashi, Navi Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0731, 73.0097),
('The Real Sindh',                    'Mulund West, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1746, 72.9550),
('The Real Sindh',                    'Vikhroli West, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1005, 72.9211),
('HandsToHeart',                      'Andheri West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1327, 72.8363),
('Shreeji Kitchens',                  'Byculla, Mumbai',                    'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9722, 72.8356),
('Tav Lunch Home',                    'Panchpakhadi, Thane',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2052, 72.9793),
('Tav Lunch Home',                    'Khopat, Thane',                      'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1940, 72.9731),
('Tav Lunch Home',                    'Charai, Thane',                      'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1887, 72.9695),
('Tav Lunch Home',                    'Thane West',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1986, 72.9662),
('Binita Ladiwala',                   'Tardeo, Mumbai',                     'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9693, 72.8175),
('Binita Ladiwala',                   'Colaba, Mumbai',                     'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9067, 72.8147),
('Meghas Kitchen',                    'Thane West',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1906, 72.9602),
('The Saoji Kitchen',                 'Vasai West',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.3659, 72.8068),
('Herbivore',                         'Mahim, Mumbai',                      'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0411, 72.8420),
('Herbivore',                         'Cuffe Parade, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9135, 72.8196),
('Herbivore',                         'Andheri West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1437, 72.8273),
('Herbivore',                         'Chembur, Mumbai',                    'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0617, 72.8992),
('Herbivore',                         'Ghatkopar East, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0840, 72.9096),
('Gogos Tiffin',                      'Grant Road, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9629, 72.8281),
('Rasoi Ghar Ki',                     'Andheri East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1259, 72.8659),
('Rasoi Ghar Ki',                     'Bandra East, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0655, 72.8551),
('Rasoi Ghar Ki',                     'Jogeshwari West, Mumbai',            'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1390, 72.8433),
('Fauram Gala',                       'Mulund East, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1737, 72.9729),
('Fauram Gala',                       'Bhandup West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1475, 72.9424),
('Fauram Gala',                       'Thane East',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1908, 72.9803),
('Zazo Foods',                        'Goregaon West, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1626, 72.8495),
('Zazo Foods',                        'Borivali East, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2325, 72.8658),
('Mom and Co',                        'Vashi, Navi Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0771, 73.0067),
('One Hot Stove',                     'Powai, Mumbai',                      'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1237, 72.9090),
('Kanak',                             'Dadar West, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0187, 72.8402),
('Ghatkopar Tiffin Service',          'Ghatkopar West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0776, 72.9040),
('Seema''s Veg Tiffin',               'Kandivali East, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2096, 72.8579),
('Seema''s Veg Tiffin',               'Borivali West, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2311, 72.8601),
('Homesome Mumbai',                   'Bandra West, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0642, 72.8335),
('Tadka Ghar Ka',                     'Malad East, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1915, 72.8605),
('Tadka Ghar Ka',                     'Borivali East, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2255, 72.8728),
('Khushboo Caterers',                 'Versova, Mumbai',                    'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1324, 72.8208),
('Indian Essence',                    'Fort, Mumbai',                       'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9358, 72.8350),
('Mystery Cravings',                  'Jogeshwari East, Mumbai',            'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1395, 72.8578),
('Mystery Cravings',                  'Bandra West, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0572, 72.8395),
('Mystery Cravings',                  'Borivali West, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2321, 72.8571),
('Parul Foods',                       'Santacruz East, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0798, 72.8542),
('Parul Foods',                       'Vile Parle East, Mumbai',            'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1014, 72.8596),
('Parul Foods',                       'Andheri East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1139, 72.8649),
('Ritu Varma',                        'Matunga West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0244, 72.8382),
('House of Nutrition',                'Wadala, Mumbai',                     'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0181, 72.8569),
('Tempt Station',                     'Kandivali West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1981, 72.8314),
('Naivedym',                          'Thane East',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1948, 72.9833),
('Soulful Sins',                      'Lokhandwala, Andheri West, Mumbai',  'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1423, 72.8293),
('Swaad by Aarti',                    'Mira Road, Mumbai',                  'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2857, 72.8558),
('Adnan and Farida',                  'Santacruz West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0845, 72.8517),
('Adnan and Farida',                  'Khar West, Mumbai',                  'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0692, 72.8329),
('Gujjubhai',                         'Ghatkopar East, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0880, 72.9056),
('Gujjubhai',                         'Tilak Nagar, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0648, 72.9041),
('Gujjubhai',                         'Chembur West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0559, 72.8945),
('Dabawali',                          'Dharavi, Mumbai',                    'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0448, 72.8547),
('Kitchen Treats',                    'Malabar Hill, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9566, 72.8054),
('Home Cooks',                        'Ghatkopar West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0816, 72.9080),
('Home Cooks',                        'Chembur East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0656, 72.9067),
('Vamas Kitchen',                     'Vile Parle West, Mumbai',            'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0990, 72.8458),
('Vamas Kitchen',                     'Irla, Mumbai',                       'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1033, 72.8333),
('SpiceBox',                          'Churchgate, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9386, 72.8241),
('SpiceBox',                          'Kandivali West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2041, 72.8354),
('Suruchi Delicacies',                'Tardeo, Mumbai',                     'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9663, 72.8205),
('Suruchi Delicacies',                'Walkeshwar, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9548, 72.7965),
('Salt N Pepper',                     'Kandivali West, Mumbai',             'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2001, 72.8364),
('Salt N Pepper',                     'Borivali East, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2265, 72.8718),
('Salt N Pepper',                     'Malad West, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1844, 72.8413),
('Shree Annapurna Tiffin Room',       'Nariman Point, Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9239, 72.8224),
('Shree Annapurna Tiffin Room',       'Andheri West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1447, 72.8303),
('Sindhi Tadka',                      'Ulhasnagar, Thane',                  'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2187, 73.1521),
('Niharika Gulati',                   'Chembur, Mumbai',                    'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0657, 72.8962),
('Kafrisa Food Co',                   'Marine Lines, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9449, 72.8228),
('Love4Palate (Shilpa)',              'Parel, Mumbai',                      'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9997, 72.8411),
('The Home Pantry',                   'Sion, Mumbai',                       'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0405, 72.8611),
('The Home Pantry',                   'Dadar East, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0211, 72.8522),
('The Home Pantry',                   'Matunga East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0253, 72.8568),
('Pataaka On Your Plate',             'Thane West',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2026, 72.9642),
('Pataaka On Your Plate',             'Lower Parel, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0015, 72.8286),
('Tasty Affair (Fatema Mohammed)',     'Cuffe Parade, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9105, 72.8226),
('Sandhya Tiffin',                    'Nana Chowk, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9645, 72.8219),
('Poonam Dua',                        'Dombivali, Thane District',          'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2158, 73.0842),
('Niharika (home chef)',              'Kalyan West',                        'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.2438, 73.1357),
('Priya Jham',                        'Nerul, Navi Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0390, 73.0173),
('Mom''s Kitchen',                    'Kharghar, Navi Mumbai',              'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0464, 73.0681),
('Yards Kitchen',                     'Panvel',                             'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9894, 73.1175),
('Poonam Tiffin',                     'Andheri West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1357, 72.8333),
('Mehroz Mukadam',                    'Andheri West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1387, 72.8353),
('Sneha (home chef)',                 'Chembur West, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0589, 72.8975),
('Enakshi Panda',                     'Chembur East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0686, 72.9037),
('Enakshi Panda',                     'Govandi, Mumbai',                    'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0573, 72.9301),
('Enakshi Panda',                     'Mankhurd, Mumbai',                   'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0500, 72.9341),
('Ashita (home chef)',                'Thane West',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1966, 72.9652),
('Neeta Patel',                       'Thane West',                         'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1926, 72.9622),
('Neeta Patel',                       'Mulund West, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1726, 72.9560),
('Harsha Punjabi',                    'Colaba, Mumbai',                     'veg', '{}', '{lunch,dinner}', false, '', true, false, 18.9097, 72.8177),
('Harsha Punjabi',                    'Dadar West, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0217, 72.8372),
('Gruhini Tiffin Services',           'Chembur, Mumbai',                    'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0637, 72.9022),
('Gruhini Tiffin Services',           'Andheri East, Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1179, 72.8719),
('Gruhini Tiffin Services',           'Powai, Mumbai',                      'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.1167, 72.9030),
('Gruhini Tiffin Services',           'Vashi, Navi Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0691, 73.0127),
('Gruhini Tiffin Services',           'Bandra Kurla Complex, Mumbai',       'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0648, 72.8645),
('Chamunda Maa Tiffin Service',       'Virar West, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.4599, 72.8098),
('Sakshi Caterers',                   'Vashi, Navi Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0711, 73.0057),
('Sakshi Caterers',                   'CBD Belapur, Navi Mumbai',           'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0246, 73.0302),
('Pitchfork',                         'Khar West, Mumbai',                  'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0722, 72.8299),
('Pitchfork',                         'Bandra West, Mumbai',                'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0582, 72.8345),
('The Diet',                          'Dadar East, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0241, 72.8492),
('Tiffin House',                      'Sanpada, Navi Mumbai',               'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0591, 73.0090),
('Happy Grub',                        'Kurla East, Mumbai',                 'veg', '{}', '{lunch,dinner}', false, '', true, false, 19.0757, 72.8892);
